services:
  db:
    image: postgres:15
    restart: always
    container_name: postgres_db_fmorpion_test
    ports:
      - $DB_HOST_PORT:$DB_CONTAINER_PORT
    env_file:
      - .env.test
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    volumes:
      - pgmorpiontest:/var/lib/postgresql/data
    networks:
      - api-fmorpion-network-test
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$DB_USERNAME"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    container_name: fmorpion_api_test
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    ports:
      - $PORT:$PORT
    env_file:
      - .env.test
    environment:
      - NODE_ENV=test
    networks:
      - api-fmorpion-network-test
    command: ["npm", "run", "test:e2e:watch"]

networks:
  api-fmorpion-network-test:
    driver: bridge

volumes:
  pgmorpiontest: